version: '2'

services:
  api:
    image: samirtalwar/bemorerandom-api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8080:8080
    env_file:
      - env/production.env
    depends_on:
      - database
      - init-db

  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data

  init-db:
    image: samirtalwar/bemorerandom-initialize-database
    build:
      context: init-db
    env_file:
      - env/production.env
    depends_on:
      - database

volumes:
  postgresql: {}
