version: '2'

services:
  api-test:
    build:
      context: .
      dockerfile: api.Dockerfile
    command:
      - 'mvn'
      - '-B'
      - 'verify'
    env_file:
      - env/test.env
    depends_on:
      - database
      - init-db

  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data

  init-db:
    build: init-db
    env_file:
      - env/test.env
    depends_on:
      - database

volumes:
  postgresql: {}
