INSERT INTO dnd_npc_first_names(name, sex, race) VALUES
    ('Azura', 'female', 'human'),
    ('Brey', 'female', 'human'),
    ('Hallan', 'female', 'human'),
    ('Anlow', 'male', 'human'),
    ('Arando', 'male', 'human'),
    ('Bram', 'male', 'human'),
    ('Artana', 'female', 'dragonborn'),
    ('Kalas', 'female', 'dragonborn'),
    ('Khagra', 'female', 'dragonborn'),
    ('Andujar', 'male', 'dragonborn'),
    ('Armagan', 'male', 'dragonborn'),
    ('Armek', 'male', 'dragonborn'),
    ('Beyla', 'female', 'dwarf'),
    ('Fenryl', 'female', 'dwarf'),
    ('Grenenzel', 'female', 'dwarf'),
    ('Agaro', 'male', 'dwarf'),
    ('Arnan', 'male', 'dwarf'),
    ('Auxlan', 'male', 'dwarf'),
    ('Allyria', 'female', 'eladrin'),
    ('Ayrdra', 'female', 'eladrin'),
    ('Deneth', 'female', 'eladrin'),
    ('Aialon', 'male', 'eladrin'),
    ('Elarahal', 'male', 'eladrin'),
    ('Jiardem', 'male', 'eladrin'),
    ('Aryllan', 'female', 'elf'),
    ('Atalya', 'female', 'elf'),
    ('Ayrthwil', 'female', 'elf'),
    ('Alarcion', 'male', 'elf'),
    ('Alathar', 'male', 'elf'),
    ('Ariandar', 'male', 'elf'),
    ('Caliope', 'female', 'halfling'),
    ('Emily', 'female', 'halfling'),
    ('Piper', 'female', 'halfling'),
    ('Arthan', 'male', 'halfling'),
    ('Carvin', 'male', 'halfling'),
    ('Corby', 'male', 'halfling'),
    ('Affyria', 'female', 'tiefling'),
    ('Cataclysmia', 'female', 'tiefling'),
    ('Domitia', 'female', 'tiefling'),
    ('Ankhus', 'male', 'tiefling'),
    ('Arkadi', 'male', 'tiefling'),
    ('Armarius', 'male', 'tiefling');

INSERT INTO dnd_npc_last_names(name, race) VALUES
    ('Arkalis', 'human'),
    ('Armanci', 'human'),
    ('Bilger', 'human'),
    ('Zethergyll', 'human'),
    ('Ambershard', 'dwarf'),
    ('Barrelhelm', 'dwarf'),
    ('Copperhearth', 'dwarf'),
    ('Lantherval', 'eladrin'),
    ('Lorhalien', 'eladrin'),
    ('Maldranthe', 'eladrin'),
    ('Autumnloft', 'elf'),
    ('Balefrost', 'elf'),
    ('Briarfell', 'elf'),
    ('Angler', 'halfling'),
    ('Battlestone', 'halfling'),
    ('Blackwater', 'halfling'),
    ('Amarzian', 'tiefling'),
    ('Carnago', 'tiefling'),
    ('Domarien', 'tiefling');
