INSERT INTO dnd_npc_first_names(name, sex, race) VALUES
    ('Azura', 'female', 'human'),
    ('Brey', 'female', 'human'),
    ('Hallan', 'female', 'human'),
    ('Kasaki', 'female', 'human'),
    ('Lorelei', 'female', 'human'),
    ('Mirabel', 'female', 'human'),
    ('Pharana', 'female', 'human'),
    ('Remora', 'female', 'human'),
    ('Rosalyn', 'female', 'human'),
    ('Sachil', 'female', 'human'),
    ('Saidi', 'female', 'human'),
    ('Tanika', 'female', 'human'),
    ('Tura', 'female', 'human'),
    ('Tylsa', 'female', 'human'),
    ('Vencia', 'female', 'human'),
    ('Xandrilla', 'female', 'human'),
    ('Anlow', 'male', 'human'),
    ('Arando', 'male', 'human'),
    ('Bram', 'male', 'human'),
    ('Cale', 'male', 'human'),
    ('Dalkon', 'male', 'human'),
    ('Daylen', 'male', 'human'),
    ('Dodd', 'male', 'human'),
    ('Dungarth', 'male', 'human'),
    ('Dyrk', 'male', 'human'),
    ('Eandro', 'male', 'human'),
    ('Falken', 'male', 'human'),
    ('Feck', 'male', 'human'),
    ('Fenton', 'male', 'human'),
    ('Gryphero', 'male', 'human'),
    ('Hagar', 'male', 'human'),
    ('Jeras', 'male', 'human'),
    ('Krynt', 'male', 'human'),
    ('Lavant', 'male', 'human'),
    ('Leyten', 'male', 'human'),
    ('Madian', 'male', 'human'),
    ('Malfier', 'male', 'human'),
    ('Markus', 'male', 'human'),
    ('Meklan', 'male', 'human'),
    ('Namen', 'male', 'human'),
    ('Navaren', 'male', 'human'),
    ('Nerle', 'male', 'human'),
    ('Nilus', 'male', 'human'),
    ('Ningyan', 'male', 'human'),
    ('Norris', 'male', 'human'),
    ('Quentin', 'male', 'human'),
    ('Semil', 'male', 'human'),
    ('Sevenson', 'male', 'human'),
    ('Steveren', 'male', 'human'),
    ('Talfen', 'male', 'human'),
    ('Tamond', 'male', 'human'),
    ('Taran', 'male', 'human'),
    ('Tavon', 'male', 'human'),
    ('Tegan', 'male', 'human'),
    ('Vanan', 'male', 'human'),
    ('Vincent', 'male', 'human'),
    ('Artana', 'female', 'dragonborn'),
    ('Kalas', 'female', 'dragonborn'),
    ('Khagra', 'female', 'dragonborn'),
    ('Leytra', 'female', 'dragonborn'),
    ('Myrka', 'female', 'dragonborn'),
    ('Naya', 'female', 'dragonborn'),
    ('Sarcha', 'female', 'dragonborn'),
    ('Shirren', 'female', 'dragonborn'),
    ('Sirivistra', 'female', 'dragonborn'),
    ('Sufana', 'female', 'dragonborn'),
    ('Tamara', 'female', 'dragonborn'),
    ('Vrumadi', 'female', 'dragonborn'),
    ('Zovra', 'female', 'dragonborn'),
    ('Andujar', 'male', 'dragonborn'),
    ('Armagan', 'male', 'dragonborn'),
    ('Armek', 'male', 'dragonborn'),
    ('Arzan', 'male', 'dragonborn'),
    ('Axaran', 'male', 'dragonborn'),
    ('Belaxarim', 'male', 'dragonborn'),
    ('Brevarr', 'male', 'dragonborn'),
    ('Djemidor', 'male', 'dragonborn'),
    ('Draxan', 'male', 'dragonborn'),
    ('Fayal', 'male', 'dragonborn'),
    ('Grax', 'male', 'dragonborn'),
    ('Iojad', 'male', 'dragonborn'),
    ('Inzul', 'male', 'dragonborn'),
    ('Khiraj', 'male', 'dragonborn'),
    ('Kreytzen', 'male', 'dragonborn'),
    ('Lejek', 'male', 'dragonborn'),
    ('Mar', 'male', 'dragonborn'),
    ('Nazir', 'male', 'dragonborn'),
    ('Nedam', 'male', 'dragonborn'),
    ('Nevek', 'male', 'dragonborn'),
    ('Ravaran', 'male', 'dragonborn'),
    ('Razaan', 'male', 'dragonborn'),
    ('Sarax', 'male', 'dragonborn'),
    ('Sarram', 'male', 'dragonborn'),
    ('Savaxis', 'male', 'dragonborn'),
    ('Siangar', 'male', 'dragonborn'),
    ('Sirizan', 'male', 'dragonborn'),
    ('Sunan', 'male', 'dragonborn'),
    ('Szuran', 'male', 'dragonborn'),
    ('Tajan', 'male', 'dragonborn'),
    ('Tamajon', 'male', 'dragonborn'),
    ('Tenahn', 'male', 'dragonborn'),
    ('Toxal', 'male', 'dragonborn'),
    ('Tzegyr', 'male', 'dragonborn'),
    ('Vantajar', 'male', 'dragonborn'),
    ('Vharkus', 'male', 'dragonborn'),
    ('Xafiq', 'male', 'dragonborn'),
    ('Zarkhil', 'male', 'dragonborn'),
    ('Beyla', 'female', 'dwarf'),
    ('Fenryl', 'female', 'dwarf'),
    ('Grenenzel', 'female', 'dwarf'),
    ('Krystolari', 'female', 'dwarf'),
    ('Lokara', 'female', 'dwarf'),
    ('Lurka', 'female', 'dwarf'),
    ('Marnia', 'female', 'dwarf'),
    ('Praxana', 'female', 'dwarf'),
    ('Rokel', 'female', 'dwarf'),
    ('Roksana', 'female', 'dwarf'),
    ('Thurlfara', 'female', 'dwarf'),
    ('Vauldra', 'female', 'dwarf'),
    ('Veklani', 'female', 'dwarf'),
    ('Vronwe', 'female', 'dwarf'),
    ('Zebel', 'female', 'dwarf'),
    ('Agaro', 'male', 'dwarf'),
    ('Arnan', 'male', 'dwarf'),
    ('Auxlan', 'male', 'dwarf'),
    ('Avamir', 'male', 'dwarf'),
    ('Baelnar', 'male', 'dwarf'),
    ('Balfam', 'male', 'dwarf'),
    ('Bariken', 'male', 'dwarf'),
    ('Borkûl', 'male', 'dwarf'),
    ('Darkûl', 'male', 'dwarf'),
    ('Dolmen', 'male', 'dwarf'),
    ('Dyrnar', 'male', 'dwarf'),
    ('Erag', 'male', 'dwarf'),
    ('Ezegan', 'male', 'dwarf'),
    ('Ferrek', 'male', 'dwarf'),
    ('Garmûl', 'male', 'dwarf'),
    ('Glint', 'male', 'dwarf'),
    ('Ghorvas', 'male', 'dwarf'),
    ('Grimmalk', 'male', 'dwarf'),
    ('Haeltar', 'male', 'dwarf'),
    ('Halagmar', 'male', 'dwarf'),
    ('Halzar', 'male', 'dwarf'),
    ('Hlant', 'male', 'dwarf'),
    ('Korlag', 'male', 'dwarf'),
    ('Krag', 'male', 'dwarf'),
    ('Krim', 'male', 'dwarf'),
    ('Kurman', 'male', 'dwarf'),
    ('Lurtrum', 'male', 'dwarf'),
    ('Malagar', 'male', 'dwarf'),
    ('Mardam', 'male', 'dwarf'),
    ('Maulnar', 'male', 'dwarf'),
    ('Melgar', 'male', 'dwarf'),
    ('Morak', 'male', 'dwarf'),
    ('Orobok', 'male', 'dwarf'),
    ('Rogath', 'male', 'dwarf'),
    ('Roken', 'male', 'dwarf'),
    ('Rozag', 'male', 'dwarf'),
    ('Sabakzar', 'male', 'dwarf'),
    ('Sharak', 'male', 'dwarf'),
    ('Smethykk', 'male', 'dwarf'),
    ('Swargar', 'male', 'dwarf'),
    ('Thorbalt', 'male', 'dwarf'),
    ('Thorin', 'male', 'dwarf'),
    ('Tredigar', 'male', 'dwarf'),
    ('Vabûl', 'male', 'dwarf'),
    ('Vistrum', 'male', 'dwarf'),
    ('Wolvar', 'male', 'dwarf'),
    ('Allyria', 'female', 'eladrin'),
    ('Ayrdra', 'female', 'eladrin'),
    ('Deneth', 'female', 'eladrin'),
    ('Elseone', 'female', 'eladrin'),
    ('Etherea', 'female', 'eladrin'),
    ('Istiria', 'female', 'eladrin'),
    ('Karanwyn', 'female', 'eladrin'),
    ('Lieryn', 'female', 'eladrin'),
    ('Ravel', 'female', 'eladrin'),
    ('Sinariel', 'female', 'eladrin'),
    ('Sydri', 'female', 'eladrin'),
    ('Taris', 'female', 'eladrin'),
    ('Turue', 'female', 'eladrin'),
    ('Vacquiel', 'female', 'eladrin'),
    ('Valendra', 'female', 'eladrin'),
    ('Aialon', 'male', 'eladrin'),
    ('Elarahal', 'male', 'eladrin'),
    ('Jiardem', 'male', 'eladrin'),
    ('Laern', 'male', 'eladrin'),
    ('Lelyrian', 'male', 'eladrin'),
    ('Lephyrr', 'male', 'eladrin'),
    ('Loray', 'male', 'eladrin'),
    ('Sayadar', 'male', 'eladrin'),
    ('Talonien', 'male', 'eladrin'),
    ('Vaerlan', 'male', 'eladrin'),
    ('Xoneras', 'male', 'eladrin'),
    ('Zaquivir', 'male', 'eladrin'),
    ('Aryllan', 'female', 'elf'),
    ('Atalya', 'female', 'elf'),
    ('Ayrthwil', 'female', 'elf'),
    ('Irva', 'female', 'elf'),
    ('Lyfalia', 'female', 'elf'),
    ('Ronefel', 'female', 'elf'),
    ('Thirya', 'female', 'elf'),
    ('Velene', 'female', 'elf'),
    ('Venefiq', 'female', 'elf'),
    ('Zereni', 'female', 'elf'),
    ('Alarcion', 'male', 'elf'),
    ('Alathar', 'male', 'elf'),
    ('Ariandar', 'male', 'elf'),
    ('Arromar', 'male', 'elf'),
    ('Borel', 'male', 'elf'),
    ('Bvachan', 'male', 'elf'),
    ('Carydion', 'male', 'elf'),
    ('Elgoth', 'male', 'elf'),
    ('Farlien', 'male', 'elf'),
    ('Ferel', 'male', 'elf'),
    ('Gaerlan', 'male', 'elf'),
    ('Iafalior', 'male', 'elf'),
    ('Kaelthorn', 'male', 'elf'),
    ('Laethan', 'male', 'elf'),
    ('Leliar', 'male', 'elf'),
    ('Leodor', 'male', 'elf'),
    ('Lorak', 'male', 'elf'),
    ('Lorifir', 'male', 'elf'),
    ('Morian', 'male', 'elf'),
    ('Oleran', 'male', 'elf'),
    ('Rylef', 'male', 'elf'),
    ('Savian', 'male', 'elf'),
    ('Seylas', 'male', 'elf'),
    ('Tevior', 'male', 'elf'),
    ('Veyas', 'male', 'elf'),
    ('Caliope', 'female', 'halfling'),
    ('Emily', 'female', 'halfling'),
    ('Piper', 'female', 'halfling'),
    ('Rixi', 'female', 'halfling'),
    ('Sabretha', 'female', 'halfling'),
    ('Teg', 'female', 'halfling'),
    ('Tilly', 'female', 'halfling'),
    ('Toira', 'female', 'halfling'),
    ('Vexia', 'female', 'halfling'),
    ('Vil', 'female', 'halfling'),
    ('Vzani', 'female', 'halfling'),
    ('Zanthe', 'female', 'halfling'),
    ('Ziza', 'female', 'halfling'),
    ('Arthan', 'male', 'halfling'),
    ('Carvin', 'male', 'halfling'),
    ('Corby', 'male', 'halfling'),
    ('Cullen', 'male', 'halfling'),
    ('Egen', 'male', 'halfling'),
    ('Ernest', 'male', 'halfling'),
    ('Gedi', 'male', 'halfling'),
    ('Heron', 'male', 'halfling'),
    ('Jeryl', 'male', 'halfling'),
    ('Keffen', 'male', 'halfling'),
    ('Kylem', 'male', 'halfling'),
    ('Kynt', 'male', 'halfling'),
    ('Leskyn', 'male', 'halfling'),
    ('Neff', 'male', 'halfling'),
    ('Orne', 'male', 'halfling'),
    ('Quarrel', 'male', 'halfling'),
    ('Rabbit', 'male', 'halfling'),
    ('Rilkin', 'male', 'halfling'),
    ('Snakebait', 'male', 'halfling'),
    ('Tarfen', 'male', 'halfling'),
    ('Titch', 'male', 'halfling'),
    ('Tuck', 'male', 'halfling'),
    ('Whim', 'male', 'halfling'),
    ('Affyria', 'female', 'tiefling'),
    ('Cataclysmia', 'female', 'tiefling'),
    ('Domitia', 'female', 'tiefling'),
    ('Dorethau', 'female', 'tiefling'),
    ('Excellence', 'female', 'tiefling'),
    ('Hacari', 'female', 'tiefling'),
    ('Iritra', 'female', 'tiefling'),
    ('Lachira', 'female', 'tiefling'),
    ('Levatra', 'female', 'tiefling'),
    ('Mecretia', 'female', 'tiefling'),
    ('Milvia', 'female', 'tiefling'),
    ('Nericia', 'female', 'tiefling'),
    ('Precious', 'female', 'tiefling'),
    ('Rain', 'female', 'tiefling'),
    ('Samantia', 'female', 'tiefling'),
    ('Sunshine', 'female', 'tiefling'),
    ('Tenerife', 'female', 'tiefling'),
    ('Traya', 'female', 'tiefling'),
    ('Velavia', 'female', 'tiefling'),
    ('Zaidi', 'female', 'tiefling'),
    ('Zethaya', 'female', 'tiefling'),
    ('Ankhus', 'male', 'tiefling'),
    ('Arkadi', 'male', 'tiefling'),
    ('Armarius', 'male', 'tiefling'),
    ('Armillius', 'male', 'tiefling'),
    ('Archidius', 'male', 'tiefling'),
    ('Balmoloch', 'male', 'tiefling'),
    ('Calderax', 'male', 'tiefling'),
    ('Cavian', 'male', 'tiefling'),
    ('Cenereth', 'male', 'tiefling'),
    ('Chorum', 'male', 'tiefling'),
    ('Corynax', 'male', 'tiefling'),
    ('Dacian', 'male', 'tiefling'),
    ('Daelius', 'male', 'tiefling'),
    ('Damaceus', 'male', 'tiefling'),
    ('Decimeth', 'male', 'tiefling'),
    ('Demedor', 'male', 'tiefling'),
    ('Demerian', 'male', 'tiefling'),
    ('Dynachus', 'male', 'tiefling'),
    ('Grassus', 'male', 'tiefling'),
    ('Halius', 'male', 'tiefling'),
    ('Heleph', 'male', 'tiefling'),
    ('Incirion', 'male', 'tiefling'),
    ('Kalaradian', 'male', 'tiefling'),
    ('Kamien', 'male', 'tiefling'),
    ('Kazimir', 'male', 'tiefling'),
    ('Kzandro', 'male', 'tiefling'),
    ('Machem', 'male', 'tiefling'),
    ('Maetheus', 'male', 'tiefling'),
    ('Malfias', 'male', 'tiefling'),
    ('Marchion', 'male', 'tiefling'),
    ('Menerus', 'male', 'tiefling'),
    ('Namazeus', 'male', 'tiefling'),
    ('Nensis', 'male', 'tiefling'),
    ('Prismeus', 'male', 'tiefling'),
    ('Pyranikus', 'male', 'tiefling'),
    ('Razortail', 'male', 'tiefling'),
    ('Sejanus', 'male', 'tiefling'),
    ('Severian', 'male', 'tiefling'),
    ('Suffer', 'male', 'tiefling'),
    ('Syken', 'male', 'tiefling'),
    ('Tarkus', 'male', 'tiefling'),
    ('Vaius', 'male', 'tiefling'),
    ('Xerek', 'male', 'tiefling'),
    ('Zeth', 'male', 'tiefling'),
    ('Zevon', 'male', 'tiefling');

INSERT INTO dnd_npc_last_names(name, race) VALUES
    ('Arkalis', 'human'),
    ('Armanci', 'human'),
    ('Bilger', 'human'),
    ('Blackstrand', 'human'),
    ('Brightwater', 'human'),
    ('Carnavon', 'human'),
    ('Caskajaro', 'human'),
    ('Coldshore', 'human'),
    ('Coyle', 'human'),
    ('Cresthill', 'human'),
    ('Cuttlescar', 'human'),
    ('Daargen', 'human'),
    ('Dalicarlia', 'human'),
    ('Danamark', 'human'),
    ('Donoghan', 'human'),
    ('Drumwind', 'human'),
    ('Dunhall', 'human'),
    ('Ereghast', 'human'),
    ('Falck', 'human'),
    ('Fallenbridge', 'human'),
    ('Faringray', 'human'),
    ('Fletcher', 'human'),
    ('Fryft', 'human'),
    ('Goldrudder', 'human'),
    ('Grantham', 'human'),
    ('Graylock', 'human'),
    ('Gullscream', 'human'),
    ('Hindergrass', 'human'),
    ('Iscalon', 'human'),
    ('Kreel', 'human'),
    ('Kroft', 'human'),
    ('Lamoth', 'human'),
    ('Leerstrom', 'human'),
    ('Lynchfield', 'human'),
    ('Moonridge', 'human'),
    ('Netheridge', 'human'),
    ('Oakenheart', 'human'),
    ('Pyncion', 'human'),
    ('Ratley', 'human'),
    ('Redraven', 'human'),
    ('Revenmar', 'human'),
    ('Roxley', 'human'),
    ('Sell', 'human'),
    ('Seratolva', 'human'),
    ('Shanks', 'human'),
    ('Shattermast', 'human'),
    ('Shaulfer', 'human'),
    ('Silvergraft', 'human'),
    ('Stavenger', 'human'),
    ('Stormchapel', 'human'),
    ('Strong', 'human'),
    ('Swiller', 'human'),
    ('Talandro ', 'human'),
    ('Targana', 'human'),
    ('Towerfall', 'human'),
    ('Umbermoor', 'human'),
    ('Van Devries', 'human'),
    ('Van Gandt', 'human'),
    ('Van Hyden', 'human'),
    ('Varcona', 'human'),
    ('Varzand', 'human'),
    ('Voortham', 'human'),
    ('Vrye', 'human'),
    ('Webb', 'human'),
    ('Welfer', 'human'),
    ('Wilxes', 'human'),
    ('Wintermere', 'human'),
    ('Wygarthe', 'human'),
    ('Zatchet', 'human'),
    ('Zethergyll', 'human'),
    ('Ambershard', 'dwarf'),
    ('Barrelhelm', 'dwarf'),
    ('Copperhearth', 'dwarf'),
    ('Deepmiddens', 'dwarf'),
    ('Drakantal', 'dwarf'),
    ('Evermead', 'dwarf'),
    ('Garkalan', 'dwarf'),
    ('Grimtor', 'dwarf'),
    ('Hackshield', 'dwarf'),
    ('Irongull', 'dwarf'),
    ('Markolak', 'dwarf'),
    ('Ramcrown', 'dwarf'),
    ('Rockharvest', 'dwarf'),
    ('Silvertarn', 'dwarf'),
    ('Skandalor', 'dwarf'),
    ('Zarkanan', 'dwarf'),
    ('Lantherval', 'eladrin'),
    ('Lorhalien', 'eladrin'),
    ('Maldranthe', 'eladrin'),
    ('Shalbarain', 'eladrin'),
    ('Sirothian', 'eladrin'),
    ('Starfeon', 'eladrin'),
    ('Zolerii', 'eladrin'),
    ('Autumnloft', 'elf'),
    ('Balefrost', 'elf'),
    ('Briarfell', 'elf'),
    ('Evenwind', 'elf'),
    ('Graytrails', 'elf'),
    ('Mooncairn', 'elf'),
    ('Riverwall', 'elf'),
    ('Stormwolf', 'elf'),
    ('Summergale', 'elf'),
    ('Sunshadow', 'elf'),
    ('Woodenhawk', 'elf'),
    ('Angler', 'halfling'),
    ('Battlestone', 'halfling'),
    ('Blackwater', 'halfling'),
    ('Daggersharp', 'halfling'),
    ('Deepstrider', 'halfling'),
    ('Hollowpot', 'halfling'),
    ('Puddle', 'halfling'),
    ('Raftmite', 'halfling'),
    ('Skiprock', 'halfling'),
    ('Silverfin', 'halfling'),
    ('Tanglestrand', 'halfling'),
    ('Tricker', 'halfling'),
    ('Willowrush', 'halfling'),
    ('Yellowcrane', 'halfling'),
    ('Amarzian', 'tiefling'),
    ('Carnago', 'tiefling'),
    ('Domarien', 'tiefling'),
    ('Iscitan', 'tiefling'),
    ('Meluzan', 'tiefling'),
    ('Menetrian', 'tiefling'),
    ('Paradas', 'tiefling'),
    ('Romazi', 'tiefling'),
    ('Sarzan', 'tiefling'),
    ('Serechor', 'tiefling'),
    ('Shadowhorn', 'tiefling'),
    ('Szereban', 'tiefling'),
    ('Torzalan', 'tiefling'),
    ('Trelenus', 'tiefling'),
    ('Trevethor', 'tiefling'),
    ('Tryphon', 'tiefling'),
    ('Vadu', 'tiefling'),
    ('Vrago.', 'tiefling');
